#!/bin/bash
# To use, place this script somewhere on the path so that it'll be found by fontforge.

argv=("$0" "$@") # $# == ${#argv[@]} + 1
last=${argv[$#]}

newwidth=$(( $(identify -format "%w" -- "$last") * 10))
newheight=$(( $(identify -format "%h" -- "$last") * 10))

args=${argv[@]:1:$#-1}
args=$(echo "$args" | sed -r 's/ -r ([0-9]+)/ -r \10/g')

cat $last | mkbitmap -s 1 |
    convert -scale "${newwidth}x${newheight}" - - |
    /usr/bin/potrace $args -a 0 -- -
