#!/bin/bash
# To use, place this script somewhere on the path so that it'll be found by fontforge.

argv=("$0" "$@") # $# == ${#argv[@]} + 1
last=${argv[$#]}

args=${argv[@]:1:$#-1}
args=$(echo "$args" | sed -r 's/ -r ([0-9]+)/ -r \10/g')

convert $last -filter point -resize 1000% BMP:- |
    /usr/bin/potrace $args -a 0 -- -
